services:
  - type: web
    name: movix-admin
    runtime: python
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn config.wsgi:application
    healthCheckPath: /login/
    envVars:
      - key: PYTHON_VERSION
        value: 3.14.6
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_PUBLIC_BUCKET
        value: movix-public
      - key: SUPABASE_PRIVATE_BUCKET
        value: movix-documents
      - key: FIREBASE_CREDENTIALS_JSON
        sync: false
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_PROVIDER
        value: brevo
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_SENDER_EMAIL
        value: eraschristopher0@gmail.com
      - key: BREVO_SENDER_NAME
        value: MOVIX
      - key: EMAIL_TIMEOUT
        value: "12"
      - key: DEFAULT_FROM_EMAIL
        value: "MOVIX <eraschristopher0@gmail.com>"
      - key: ALLOWED_HOSTS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
