# Generated by Django 6.0.8 on 2026-08-11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0003_advertisement_auditlog_devicetoken_driverreview_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverMonthlyPayment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("period", models.DateField()),
                ("amount", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("bank", models.TextField()),
                ("payment_method", models.TextField(default="transfer")),
                ("receipt_url", models.TextField(blank=True, null=True)),
                ("status", models.TextField(default="pending")),
                ("admin_notes", models.TextField(blank=True, null=True)),
                ("reviewed_by", models.TextField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "driver_monthly_payments",
                "ordering": ["-period", "-created_at"],
                "managed": False,
            },
        ),
    ]
