# Generated by Django 6.0.8 on 2026-08-11 02:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_drivermonthlypayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverInboxMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('message_type', models.TextField(choices=[('invoice', 'Factura'), ('meeting', 'Reunión'), ('payment', 'Pago'), ('account', 'Cuenta'), ('general', 'General')], default='general')),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'driver_inbox_messages',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DriverInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('invoice_number', models.TextField(unique=True)),
                ('customer_name', models.TextField()),
                ('customer_email', models.TextField(blank=True, null=True)),
                ('customer_identification', models.TextField(blank=True, null=True)),
                ('period', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank', models.TextField()),
                ('payment_method', models.TextField()),
                ('pdf_url', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='issued')),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'driver_invoices',
                'ordering': ['-issued_at', '-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentBankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.TextField(choices=[('banco_loja', 'Banco de Loja'), ('banco_pichincha', 'Banco Pichincha'), ('coopego', 'Banco Coopego'), ('jep', 'Cooperativa JEP')], unique=True)),
                ('account_holder', models.TextField()),
                ('account_number', models.TextField()),
                ('account_type', models.TextField(choices=[('savings', 'Ahorros'), ('checking', 'Corriente')], default='savings')),
                ('identification_number', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('qr_url', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment_bank_accounts',
                'ordering': ['sort_order', 'code'],
                'managed': False,
            },
        ),
    ]
