# Generated by Django 6.0.8 on 2026-08-24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("panel", "0006_profile_is_blocked")]

    operations = [
        migrations.CreateModel(
            name="FleetDriver",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("first_name", models.TextField()), ("last_name", models.TextField()),
                ("identification_number", models.TextField()), ("license_number", models.TextField()),
                ("phone", models.TextField(blank=True, null=True)), ("email", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)), ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"db_table": "fleet_drivers", "ordering": ["first_name", "last_name"], "managed": False},
        ),
        migrations.CreateModel(
            name="FleetVehicle",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("plate", models.TextField()), ("vehicle_type", models.TextField()),
                ("year", models.IntegerField(blank=True, null=True)),
                ("load_capacity", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("alias", models.TextField(blank=True, null=True)), ("permit_number", models.TextField(blank=True, null=True)),
                ("photo_url", models.TextField(blank=True, null=True)), ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)), ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"db_table": "fleet_vehicles", "ordering": ["plate"], "managed": False},
        ),
        migrations.CreateModel(
            name="RideStop",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("stop_type", models.TextField()), ("sequence", models.PositiveIntegerField(default=1)),
                ("address", models.TextField()), ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)), ("contact_name", models.TextField(blank=True, null=True)),
                ("contact_phone", models.TextField(blank=True, null=True)), ("notes", models.TextField(blank=True, null=True)),
                ("status", models.TextField(default="pending")), ("arrived_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)), ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"db_table": "ride_stops", "ordering": ["sequence", "created_at"], "managed": False},
        ),
    ]
