# Generated by Django 6.0.8 on 2026-08-24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("panel", "0007_fleetdriver_fleetvehicle_ridestop")]

    operations = [
        migrations.CreateModel(
            name="AdminNotification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("type", models.TextField(default="general")),
                ("title", models.TextField()),
                ("message", models.TextField()),
                ("target_url", models.TextField(blank=True, null=True)),
                ("entity_type", models.TextField(blank=True, null=True)),
                ("entity_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"db_table": "admin_notifications", "ordering": ["-created_at"], "managed": False},
        ),
    ]
