from django.urls import path

from . import views


app_name = "panel"

urlpatterns = [
    path("", views.landing, name="landing"),
    path("demo/", views.demo_app, name="demo"),
    path("auth/callback/", views.auth_callback, name="auth_callback"),
    path("auth/session/", views.auth_session, name="auth_session"),
    path("transportista/", views.driver_dashboard, name="driver_dashboard"),
    path("transportista/carreras/", views.driver_rides, name="driver_rides"),
    path("transportista/carreras/<uuid:ride_id>/", views.driver_ride_detail, name="driver_ride_detail"),
    path("transportista/comentarios/", views.driver_reviews, name="driver_reviews"),
    path("transportista/perfil/", views.driver_profile, name="driver_profile"),
    path("transportista/mensualidad/", views.driver_payments, name="driver_payments"),
    path("transportista/facturas/", views.driver_invoices, name="driver_invoices"),
    path("transportista/buzon/", views.driver_inbox, name="driver_inbox"),
    path("transportista/buzon/<uuid:message_id>/", views.driver_inbox_detail, name="driver_inbox_detail"),
    path("administracion/", views.dashboard, name="dashboard"),
    path("buscar/", views.global_search, name="search"),
    path("solicitudes/", views.contact_request_list, name="contact_request_list"),
    path("solicitudes/<uuid:request_id>/", views.contact_request_detail, name="contact_request_detail"),
    path("solicitudes/<uuid:request_id>/estado/<str:status>/", views.contact_request_status, name="contact_request_status"),
    path("personas/<str:kind>/", views.profile_list, name="profile_list"),
    path("personas/<str:kind>/nuevo/", views.profile_create, name="profile_create"),
    path("personas/<str:kind>/exportar/", views.profile_export, name="profile_export"),
    path("personas/<str:kind>/<uuid:profile_id>/", views.profile_detail, name="profile_detail"),
    path("personas/<str:kind>/<uuid:profile_id>/editar/", views.profile_edit, name="profile_edit"),
    path("personas/<str:kind>/<uuid:profile_id>/eliminar/", views.profile_delete, name="profile_delete"),
    path("personas/<str:kind>/<uuid:profile_id>/estado/", views.profile_toggle, name="profile_toggle"),
    path("verificaciones/", views.verification_list, name="verification_list"),
    path("verificaciones/<uuid:profile_id>/", views.verification_detail, name="verification_detail"),
    path("verificaciones/<uuid:profile_id>/<str:decision>/", views.verification_update, name="verification_update"),
    path("archivos/<uuid:profile_id>/<str:document_key>/<str:action>/", views.document_access, name="document_access"),
    path("mensualidades/", views.monthly_payment_list, name="monthly_payment_list"),
    path("mensualidades/<uuid:payment_id>/", views.monthly_payment_detail, name="monthly_payment_detail"),
    path("mensualidades/<uuid:payment_id>/factura/", views.monthly_payment_invoice, name="monthly_payment_invoice"),
    path("mensualidades/<uuid:payment_id>/<str:decision>/", views.monthly_payment_review, name="monthly_payment_review"),
    path("mensualidades/comprobante/<uuid:payment_id>/<str:action>/", views.monthly_payment_receipt, name="monthly_payment_receipt"),
    path("mensualidades/transportista/<uuid:profile_id>/fisico/", views.monthly_payment_physical, name="monthly_payment_physical"),
    path("mensualidades/transportista/<uuid:profile_id>/<str:action>/", views.driver_payment_block, name="driver_payment_block"),
    path("mensualidades/bancos/", views.payment_bank_accounts, name="payment_bank_accounts"),
    path("mensualidades/bancos/<uuid:bank_id>/estado/", views.payment_bank_toggle, name="payment_bank_toggle"),
    path("mensualidades/bancos/<uuid:bank_id>/<str:asset>/<str:action>/", views.payment_bank_asset, name="payment_bank_asset"),
    path("mensualidades/mensajes/", views.admin_driver_messages, name="admin_driver_messages"),
    path("mensualidades/facturas/<uuid:invoice_id>/<str:action>/", views.driver_invoice_file, name="driver_invoice_file"),
    path("notificaciones/", views.notifications_view, name="notifications"),
    path("publicidad/", views.advertisements_view, name="advertisements"),
    path("publicidad/<uuid:advertisement_id>/estado/", views.advertisement_toggle, name="advertisement_toggle"),
    path("publicidad/<uuid:advertisement_id>/eliminar/", views.advertisement_delete, name="advertisement_delete"),
    path("perfil/", views.admin_profile_view, name="admin_profile"),
    path("perfil/eliminar/", views.admin_account_delete, name="admin_account_delete"),
    path("configuracion/", views.settings_view, name="settings"),
]
